name: Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 1,15 * *" # the 1st and the 15th of every month at 1:30 AM

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: identify 4 latest releases
        run: |
          gh api "/repos/${{ github.repository_owner }}/${{ github.repository }}/releases?per_page=4" --jq "{release_tag: map( .tag_name )}" > matrix.json
          cat ./matrix.json
          matrixJSON="$(cat ./matrix.json)"
          echo "::set-output name=matrix::$matrixJSON"

  buildandpush:
    needs: prepare
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}

    steps:
      - name: checkout branch for schedule event
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.release_tag }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: |
          make docker-push-all

