name: Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 1,15 * *" # the 1st and the 15th of every month at 1:30 AM

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - id: releases
        run: |
          set -eux
          JSON=$(gh api "/repos/charbonnierg/demo-dynamic-matrix/releases?per_page=4" | jq -c "map( .tag_name )")
          echo "TAGS=$JSON" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
    # Reference: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    outputs:
      TAGS: ${{ steps.releases.outputs.TAGS }}

  build:
    needs: [prepare]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        release_tag: ${{ fromJson(needs.prepare.outputs.TAGS) }}

    steps:
      - name: checkout branch for schedule event
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.release_tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: |
          make docker-push-all
